### ISSUE TITLE
/team出问题

### ISSUE THREAD

**Issue by 3545game** [wifi-left/Map-MiniGames-old#10]
用了原版fa端，自检还是说/team有问题，很多游戏也无法进行，说人数不够

**Comment by wifi-left** [comment]
请问解决了吗？如果没有，请尝试重新下载地图。
目前不知道什么缘故，地图开一段时间后服务器会特别卡顿。
出现这种情况时，请直接删档重开（暂时没找到原因）

**Comment by 3545game** [comment]
装了carpet后得到了解决
