### ISSUE TITLE
[Bug] bw道具tnt无法购买

### ISSUE THREAD

**Issue by Guailoudou** [wifi-left/Map-MiniGames-old#13]
### 服务端信息

fabric 1.21 Velocity

### 客户端信息

原版1.21

### 问题描述

bw tnt道具无法购买，点击后就直接拿出来了，其他物品都正常

**Comment by wifi-left** [comment]
已在本地复现并修复。请等待近期最新版，将会与新游戏一同更新。

**Comment by wifi-left** [comment]
近期新游戏不会实装，我先更新一下把bug修了吧
