### ISSUE TITLE
[Bug] BoatWar模式下玩家射击可以击中旁观者

### ISSUE THREAD

**Issue by yizhi9jiyan9** [wifi-left/Map-MiniGames-old#15]
### 服务端信息

1.21.1fabric 无mod
小游戏版本：MC1.21.1.21.1.MiniGames_2024_09_21

### 客户端信息

1.21.1fabric

### 问题描述

玩家在使用枪械射击时，射出的子弹可以击中旁观者
显示：击中目标，剩余血量：
使玩家无法击中敌人

**Comment by wifi-left** [comment]
收到，正在排拆

**Comment by wifi-left** [comment]
已修复
