### ISSUE TITLE
[2022.09.12] 服务器地图bug #2

### ISSUE THREAD

**Issue by DomnickJYH** [wifi-left/Map-MiniGames-old#2]
玩起床的时候在确认准备好，全员分好队（大概）的时候随机有人掉线（请问这样的描述可以吗？）

**Comment by wifi-left** [comment]
此问题不算地图问题
因为地图设计是给20人以内的玩家设计的，超过20人出现问题我也无能为力（很可能是服务器算不过来就把玩家剔了）

**Comment by wifi-left** [comment]
如果我有能力我会解决的
