### ISSUE TITLE
[建议][起床战争] 添加时间限制

### ISSUE THREAD

**Issue by DomnickJYH** [wifi-left/Map-MiniGames-old#3]
起床战争可以设置一个有时间限制床自动爆炸的模式，要不然有时候打太久，已经寄了的队伍没有游戏体验

**Comment by wifi-left** [comment]
已完成
in https://github.com/wifi-left/Map-MiniGames/commit/2661e8d79dbd56e655d6f2ac221eb53f81c65e6b
