### ISSUE TITLE
关于一个新模式[tnt大战]的提议

### ISSUE THREAD

**Issue by RyahoSolomon** [wifi-left/Map-MiniGames-old#6]
很早以前在一个主播频道看到的玩法,原视频找不到了,抱歉
简单来说就是两队各有一艘空中船,玩家可以每隔几秒向前发射一个tnt,可以破坏船体,把对方炸死或者炸下虚空取得胜利
我曾利用匠魂模组的投掷炸弹实现过这个小游戏,如果大佬需要更详细的玩法我可以找机会给它录个视频
希望您能够采纳提议并把它做出来,多谢!

**Comment by wifi-left** [comment]
不太理解。能否描述的详细一点？

**Comment by RyahoSolomon** [comment]
游戏流程:
①玩家被分为两队,双方分别在一条空中的船上,两条船不连接,**不能直接攻击到对手**
②每隔几秒,双方就会获得一个道具,使用后能向前发射一个炸弹
③这个炸弹**可以破坏船体,破坏对方的落脚处**
④当某队玩家全部掉入虚空/被炸死之后,另一队胜利
以下是我在我利用匠魂模组做出来的地图中录制的游玩视频(约90MB)
链接：https://pan.baidu.com/s/1LHRW3eYqQTcoT9dLLdaMKw 
提取码：bpdz
ps:视频中的船只用的是木板导致淘汰过快,实际地图用爆破抗性更高的方块可以使游戏节奏更合理
如果大佬认为这个玩法具备足够可玩性的话,还请您在地图中加入这个模式,还可以对玩法修改或加入其它的细节.
谢谢!
(注:炸弹有没有伤害都可,如果炸弹有伤害的话,不宜过高,以击落对手为主)

**Comment by wifi-left** [comment]
行，准备做了
不过，是只能破坏方块还是说玩家可以PVP然后导致受伤？

**Comment by RyahoSolomon** [comment]
只能通过炸弹造成伤害,炸弹的伤害也可有可无,如果炸弹有伤害的话,不宜太高,以击落或者破坏对手落脚点为主
无法pvp,严格来说地图设计上两队分别在各自的船上无法接触,从而无法pvp
不过您有什么想法也都可以的

**Comment by wifi-left** [comment]
已完成。
https://github.com/wifi-left/Map-MiniGames/commit/80a2eef9841e685f3fc331621339f360cefbac6c

**Comment by wifi-left** [comment]
话说，能给下视频中的两艘船嘛
看着还挺不错的（）
