### ISSUE TITLE
关于一个新模式[船战(2队模式)]的提议

### ISSUE THREAD

**Issue by wkkkkkk-kkk** [wifi-left/Map-MiniGames-old#7]
简介:
玩家通过击败对手的船来获取金币以购买船只、枪支、炮弹
不同的船只血量不同，技能也不同
玩家只能通过枪支炮弹来击败敌人的船只，并且游戏中的玩家隐身，船只上通过盔甲架或其他东西显示血量及玩家名
在击败敌方全部船只后即可获胜
不同的队伍船只颜色不一
玩家在游戏中下船将被踢出游戏，踢出前将给予5秒的时间回到船上以继续游戏，防止误触降低游戏体验
游戏地图中可根据实际情况搭建一些遮挡物
击杀队友无效
游戏流程:
①在每位玩家都放置好船只并上船后即可加入队伍，在人数均衡的时候倒数15秒后开始游戏，玩家将被均衡分配在两支队伍
②每隔几秒玩家就会活的一定量的金币，长时间不移动的玩家不给予
③炮弹须瞄准敌方船只并击中才可以对其造成伤害，击中上半部分（玩家部分）无效
④玩家将根据船只配置在一定的时间内恢复一定的血量
⑤击败其他船只后将获得金币奖励
⑥当某队玩家全部被击败后另一队胜利
注:金币是累积的不会因为新的一局而清空

**Comment by wifi-left** [comment]
打算做，可能在近期更新（？）

**Comment by wifi-left** [comment]
更新
