### ISSUE TITLE
划船比赛无法开启游戏

### ISSUE THREAD

**Issue by tianyimc** [wifi-left/Map-MiniGames-old#9]
人数已经到达两人，提示需要至少等待2人
8月20版本

**Comment by wifi-left** [comment]
请确认：
1. 您所使用的服务端为 fabric服务端、原版服务端、spigot服务端（不支持paper服务端）
2. 您没有加任何类似于ess的插件、mod
3. ~~您是从GitLab或者GitHub下载的~~（可忽略）
4. 您不是直接tp玩家进入游戏等待区域的
5. 您和其他玩家的游戏模式为冒险模式

**Comment by wifi-left** [comment]
一般而言，如果正常使用地图，多半是由于您使用 Paper以及其衍生服务端得锅。

> Paper 服务端会吞掉队伍，导致玩家人数检测失败

~~Paper的“优化”是真的好，直接把小游戏地图的大部分游戏功能优化没了。~~

**Comment by tianyimc** [comment]
![image](https://github.com/wifi-left/Map-MiniGames/assets/122505964/973c21be-3612-4f77-8e7a-9d829914e72e)
您好！感谢您的回复。我使用的是Spigot，添加的插件如图，我通过Gitlab下载了最新版本的地图，我和玩家都正常地进入游戏，我已知的可能性问题是玩家可能没有安装资源包，但我并不确定资源包是否是必要的，以及是否会导致这样的问题。另外，该问题不仅出现于划船比赛，一些小游戏也会出现这样的问题，但不是所有多人小游戏都会出现。

**Comment by wifi-left** [comment]
请尝试删除所有插件后重试。

**Comment by wifi-left** [comment]
我只能保证地图与原版spigot端进行适配，并不能保证与插件适配
如果是spigot的问题导致的地图问题，本人也不会主动去修复，除非找到解决办法

**Comment by wifi-left** [comment]
顺带一提，貌似部分皮肤模组会导致问题，我也不知道是不是真的

**Comment by wifi-left** [comment]
如果还有问题可以来q群问：958572618

**Comment by wifi-left** [comment]
资源包并不是必要的

**Comment by wifi-left** [comment]
您好，请问问题解决了吗

**Comment by wifi-left** [comment]
如果还有问题请重新提起issue，我把issue关了哈。
paper了话需要关掉自动删除队伍的选项，详情请见mccbs帖子
